### ISSUE TITLE
你好，虎扑过来的。。。你确定试过在新的电脑上能导入到android studio吗

### ISSUE THREAD

**Issue by huanghaoming** [zion223/NeteaseCloudMusic#3]
好像环境部署依赖方面还没完善
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all artifacts for configuration ':classpath'.

Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.2.0).

看build里还有私服仓库的配置。。这叫人怎么跑起来。。

**Comment by zion223** [comment]
build 里面私服的配置是用不到的哈，我查了下这个貌似是Androidstudio版本兼容问题，我现在用的是3.6.3的版本。

**Comment by huanghaoming** [comment]
哈哈，我用的也是363版本，但是却出现这个问题，我觉得你可以找个新的环境试一下导入



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zion223 <notifications@github.com&gt;
发送时间: 2020年5月2日 07:42
收件人: zion223/NeteaseCloudMusic <NeteaseCloudMusic@noreply.github.com&gt;
抄送: huanghaoming <1585685035@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zion223/NeteaseCloudMusic] 你好，虎扑过来的。。。你确定试过在新的电脑上能导入到android studio吗 (#3)

**Comment by zion223** [comment]
我这只有一台电脑，刚才重新clone到本地一份重新导入AS也是没有问题的。

**Comment by huanghaoming** [comment]
那就奇怪了哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zion223 <notifications@github.com&gt;
发送时间: 2020年5月2日 08:14
收件人: zion223/NeteaseCloudMusic <NeteaseCloudMusic@noreply.github.com&gt;
抄送: huanghaoming <1585685035@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zion223/NeteaseCloudMusic] 你好，虎扑过来的。。。你确定试过在新的电脑上能导入到android studio吗 (#3)

**Comment by huanghaoming** [comment]
那有apk吗，我下载来体验一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zion223 <notifications@github.com&gt;
发送时间: 2020年5月2日 08:14
收件人: zion223/NeteaseCloudMusic <NeteaseCloudMusic@noreply.github.com&gt;
抄送: huanghaoming <1585685035@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zion223/NeteaseCloudMusic] 你好，虎扑过来的。。。你确定试过在新的电脑上能导入到android studio吗 (#3)

**Comment by zion223** [comment]
邮件发你吧，留个邮箱吧。

**Comment by huanghaoming** [comment]
1585685035。 &nbsp;qq的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zion223 <notifications@github.com&gt;
发送时间: 2020年5月2日 08:45
收件人: zion223/NeteaseCloudMusic <NeteaseCloudMusic@noreply.github.com&gt;
抄送: huanghaoming <1585685035@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zion223/NeteaseCloudMusic] 你好，虎扑过来的。。。你确定试过在新的电脑上能导入到android studio吗 (#3)
