### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by TheBugAgain** [zion223/NeteaseCloudMusic#5]

**Comment by zion223** [comment]
切换到oldapi分支,拉去最新代码。

**Comment by TheBugAgain** [comment]
昨天没看评论  后来看了评论已经弄好了------------------ 原始邮件 ------------------
发件人: "zion223"<notifications@github.com>
发送时间: 2020年5月16日(星期六) 中午12:23
收件人: "zion223/NeteaseCloudMusic"<NeteaseCloudMusic@noreply.github.com>;
抄送: "brined Fish"<1756489713@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zion223/NeteaseCloudMusic] 缺少文件 (#5)




 
切换到oldapi分支,拉去最新代码。
 
&mdash;
