### ISSUE TITLE
项目在Android Studio倒入失败

### ISSUE THREAD

**Issue by bigdogs** [zion223/NeteaseCloudMusic#6]
Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.2.0).
Searched in the following locations:
    https://maven.aliyun.com/repository/google/com/android/tools/analytics-library/tracker/26.2.0/tracker-26.2.0.jar

**Comment by bigdogs** [comment]
切换到oldapi后又会出现异常启动不了:
2020-06-04 11:52:27.311 7079-7079/com.imooc.imooc_voice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imooc.imooc_voice, PID: 7079
    java.lang.RuntimeException: Canvas: trying to draw too large(118964160bytes) bitmap.

**Comment by zion223** [comment]
应该是我的drawable文件夹没有根据分辨率分类，然后分辨率太高的话一加载就OOM了

**Comment by bigdogs** [comment]
目前切换到oldapi分支， 在manifest里面关闭硬件加速就可以运行起来了
