### ISSUE TITLE
Android Studio中无法打开

### ISSUE THREAD

**Issue by flenzero** [zion223/NeteaseCloudMusic#9]
我在android studio中打开会报错（且暂时找不到解决办法）：Cause: processResources.sourceOutputDir must not be null
求解如何在android studio中打开

**Comment by zion223** [comment]
没遇到过这种情况

**Comment by baoning2019** [comment]
Caused by: java.lang.IllegalStateException: processResources.sourceOutputDir must not be null

**Comment by happylee1** [comment]
> 没遇到过这种情况

在没有升级Gradle Plugin和Gradle之前，项目是可以正常编译运行的，但是如果按照Android Studio提示，升级Gradle Plugin和Gradle之后就会出现该报错。

**Comment by happylee1** [comment]
> 没遇到过这种情况

下图是wo我把NeteaseCloudMusic-newapi项目导入到Android Studio后出现的升级提示，如果忽略这个升级提示，项目还是可以正常编译运行的，但是现在慕课云音乐已经没法正常登陆了，还想请教一下博主，麻烦您了。
<img width="1104" alt="update_notification" src="https://user-images.githubusercontent.com/28051469/99906785-fb610480-2d13-11eb-9282-f42de4b8e1c9.png">

**Comment by zion223** [comment]
> > 没遇到过这种情况
> 
> 下图是wo我把NeteaseCloudMusic-newapi项目导入到Android Studio后出现的升级提示，如果忽略这个升级提示，项目还是可以正常编译运行的，但是现在慕课云音乐已经没法正常登陆了，还想请教一下博主，麻烦您了。
> <img alt="update_notification" width="1104" src="https://user-images.githubusercontent.com/28051469/99906785-fb610480-2d13-11eb-9282-f42de4b8e1c9.png">

服务器到期了 我没有续费 所以无法正常登陆了。
